name: Code Formatting

on:
  push:
    branches:
      - main # Replace "main" with the name of your default branch if it's different
  pull_request:
    types:
      - closed
    branches:
      - main # Replace "main" with the name of your default branch if it's different

jobs:
  format_code:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm run format # Replace "format" with the script in your package.json that formats your code

      - name: Commit formatted code
        run: |
          git diff --exit-code || (
            git config --global user.name 'GitHub Action'
            git config --global user.email 'github-action@users.noreply.github.com'
            git add .
            git commit -m "Format code"
            git push
          )
